# Project: semana 1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "2\ semestre/semana01/main.o" "2\ semestre/semana01/Carro.o" "2\ semestre/semana01/Livro.o" "2\ semestre/semana01/Motor.o"
LINKOBJ  = "2 semestre/semana01/main.o" "2 semestre/semana01/Carro.o" "2 semestre/semana01/Livro.o" "2 semestre/semana01/Motor.o"
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "semana 1.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"2\ semestre/semana01/main.o": 2\ semestre/semana01/main.cpp
	$(CPP) -c "2 semestre/semana01/main.cpp" -o "2 semestre/semana01/main.o" $(CXXFLAGS)

"2\ semestre/semana01/Carro.o": 2\ semestre/semana01/Carro.cpp
	$(CPP) -c "2 semestre/semana01/Carro.cpp" -o "2 semestre/semana01/Carro.o" $(CXXFLAGS)

"2\ semestre/semana01/Livro.o": 2\ semestre/semana01/Livro.cpp
	$(CPP) -c "2 semestre/semana01/Livro.cpp" -o "2 semestre/semana01/Livro.o" $(CXXFLAGS)

"2\ semestre/semana01/Motor.o": 2\ semestre/semana01/Motor.cpp
	$(CPP) -c "2 semestre/semana01/Motor.cpp" -o "2 semestre/semana01/Motor.o" $(CXXFLAGS)
